<template>
  <div>
    <div class="title" style="margin-top:0px">单用户下载情况统计</div>
    <div class="block">
      <div style="margin-right:20px">时间范围:</div>
      <div >
        <el-date-picker
          v-model="value1"
          type="date"
          id="value1"
          placeholder="选择日期">
        </el-date-picker>
        <span>—</span>
        <el-date-picker
          v-model="value2"
          type="date"
          id="value2"
          placeholder="选择日期">
        </el-date-picker>
        <el-button icon="el-icon-search" type="primary" size="small" style="margin-left:20px" @click="resultcenterdata">查询</el-button>
        <el-button type="primary" size="small" @click="exportExcel">导出</el-button>
      </div>
    </div>
    <div style="padding: 0 20px;">
      <el-table
        id="tb"
        v-if="isShowTable"
        :data="ReportformData"
        style="width: 100%;">
        <el-table-column
          type="index"
          label="序号"
          width="60px"
        >
        </el-table-column>
        <el-table-column
          prop="name"
          label="机构名称"
          width="300">
        </el-table-column>
        <el-table-column
          prop="user"
          label="用户名">
        </el-table-column>
        <el-table-column
          prop="total"
          label="总量">
        </el-table-column>
        <el-table-column label="知识专区">
          <el-table-column v-for="(item, index) in formHeader" :key="index" :prop="item.MENUNAME + '.FILENUM'" :label="item.MENUNAME"></el-table-column>
        </el-table-column>
        <el-table-column label="数据专区">
          <el-table-column v-for="(item, index) in sjformHeader" :key="index" :prop="item.MENUNAME + '.FILENUM'" :label="item.MENUNAME"></el-table-column>
        </el-table-column>
      </el-table>
      <div v-else-if="isShowTable == false">数据正在努力加载中...</div>
    </div>
  </div>
  
</template>

<script>
  import XLSX from 'xlsx';
  export default {
    data() {
      return {
        formHeader:[],
        sjformHeader: [],
        header:[],
        ReportformData:[],
        artic:{
          beginDate:'',
          endDate:''
        },
        value1: '',
        value2: '',
        isShowTable: false,
        downloadNum:[
          {
            "人力资源部（党委组织部）":[
              {
                "FILESIZE":13,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":19
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "计划财务部":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":14
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "党委党建工作部（监察室）":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":16
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "战略规划研究中心":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":13
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "金融研究中心":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":11
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "技术应用研究中心":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":11
              },
              {
                "FILESIZE":781.5144,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":15
              },
              {
                "FILESIZE":505.0166,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":3
              },
              {
                "FILESIZE":29.0967,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":3
              },
              {
                "FILESIZE":141.9358,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":2
              },
              {
                "FILESIZE":26.9890,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":3
              },
              {
                "FILESIZE":75.2438,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":2
              },
              {
                "FILESIZE":3.2325,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":2
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "设计中心（中国邮政集团公司定额站）":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":11
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "质量检测与标准研究中心":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":12
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "科研管理部":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":14
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "开发一部":[
              {
                "FILESIZE":0.0000,
                "MENUID":15,
                "MENUNAME":"用户名",
                "FILENUM":12
              },
              {
                "FILESIZE":0.0000,
                "MENUID":0,
                "MENUNAME":"总量",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":1,
                "MENUNAME":"论文",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":2,
                "MENUNAME":"案例",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":3,
                "MENUNAME":"成果",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":4,
                "MENUNAME":"图书",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":5,
                "MENUNAME":"知识产权",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":6,
                "MENUNAME":"标准",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":7,
                "MENUNAME":"实验室",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":8,
                "MENUNAME":"图片",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":9,
                "MENUNAME":"视频",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":11,
                "MENUNAME":"科研",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":12,
                "MENUNAME":"宏观",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":13,
                "MENUNAME":"金融",
                "FILENUM":0
              },
              {
                "FILESIZE":0.0000,
                "MENUID":14,
                "MENUNAME":"物流",
                "FILENUM":0
              }
            ]
          },
          {
            "总量":[
              {
                "TOTALSIZE":781.5144,
                "TOTALCOUNT":15
              }
            ]
          }
        ]
      }
    },
    mounted() {
      this.resultcenterdata();
    },
    methods: {
      resultcenterdata(){
        let that = this;
        this.artic.endDate = $('#value2').val();
        this.artic.beginDate =$('#value1').val();
        var arr = [];
        arr = this.downloadNum.map(item => {
          let name = Object.keys(item)[0];
          let array = item[name];
          let obj = {name: name};
          array.forEach(item1 => {
            obj[item1.MENUNAME] = item1;
            if(item1.MENUNAME == '总量') {
              obj.total = item1.FILENUM;
            }
            if(item1.MENUNAME == '用户名'){
              obj.user = item1.FILENUM;
            }
          })
          return obj;
        });
        arr.splice(arr.length - 1, 1);
        this.ReportformData = arr;
        // 此步骤知识为了取到二级表头的表头文本内容，进行循环渲染，跟机构无关
        let zsArr = this.downloadNum[0][arr[0].name];
        let sjArr = this.downloadNum[0][arr[0].name];
        console.log(zsArr)
        if(zsArr.length == 15) { //知识专区
          this.formHeader = zsArr.slice(2,11);
          console.log(this.formHeader)
        }
        if(sjArr.length == 15) {//数据专区
          this.sjformHeader = sjArr.slice(11,15); //删除前十个知识专区的数据
        }
        this.isShowTable = true;

      },
      // 导出表格
      exportExcel() {
        const tb = document.getElementById('tb');
        let sheet = XLSX.utils.table_to_sheet(tb);
        saveAs(sheet2blob(sheet), '单用户上传情况统计.xlsx');

        function saveAs(obj, fileName) {
          const a = document.createElement('a');
          document.body.appendChild(a);
          a.download = fileName || '下载';
          a.href = URL.createObjectURL(obj);
          a.click();
          setTimeout(() => {
            URL.revokeObjectURL(obj);
            document.body.removeChild(a);
          }, 100);
        };

        // 将一个sheet转成最终的excel文件的blob对象，然后利用URL.createObjectURL下载
        function sheet2blob(sheet, sheetName) {
          sheetName = sheetName || 'sheet1';
          let workbook = {
            SheetNames: [sheetName],
            Sheets: {}
          };
          workbook.Sheets[sheetName] = sheet;
          // 生成excel的配置项
          let wopts = {
            bookType: 'xlsx', // 要生成的文件类型
            bookSST: false, // 是否生成Shared String Table，官方解释是，如果开启生成速度会下降，但在低版本IOS设备上有更好的兼容性
            type: 'binary'
          };
          let wbout = XLSX.write(workbook, wopts);
          let blob = new Blob([s2ab(wbout)], {type: "application/octet-stream"});

          // 字符串转ArrayBuffer
          function s2ab(s) {
            let buf = new ArrayBuffer(s.length);
            let view = new Uint8Array(buf);
            for (let i = 0; i != s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
          }

          return blob;
        }
      },
    },
  }
</script>

<style scoped rel="stylesheet/scss" lang="scss">
  .block {
    display: flex;
    align-items: center;
    padding: 20px
  }
</style>
